_target_: navsim.common.dataclasses.SceneFilter
_convert_: 'all'

num_history_frames: 4
num_future_frames: 10
frame_interval: null
has_route: true

max_scenes: null
log_names:
  - "2021.06.28.16.29.11_veh-38_01415_01821"
  - "2021.10.11.02.57.41_veh-50_01522_02088"
tokens: null
